variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  CI_DEBUG_TRACE: "false"

stages:
  - build
  - test
 
build:
  stage: build
  image: golang:latest
  script:
    - cd $CI_PROJECT_DIR/driver
    - go version
    - export GOARCH=amd64
    - export GOOS=linux
    - go install
    - export GOARCH=amd64
    - export GOOS=windows
    - go install

.test_template: &test_definition
  stage: test
  script:
    - export GOHDBDSN=$GO_HANA_DSN
    - go test -v ./...
    - export GOHDBDSN=$GO_HANA_TLS_DSN
    - go test -v ./...

golang_1_13_10:
  image: golang:1.13.8
  <<: *test_definition
  
golang_1_14_2:
  image: golang:1.14.2
  <<: *test_definition
